spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Edson-brenno/ConfigRepositorioService
          search-paths:
            - estudante-service
            - sala-service
            - naming-server
            - api-gateway
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
